[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = ['VimEnter']
depends = [
    'denops.vim',
    'mason.nvim',
    'denops.vim',
    'skkeleton',
]
lua_source = "require('plugins.ddc')"

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
on_event = ['VimEnter']
depends = [
    'denops.vim',
]
lua_source = "require('plugins.skkeleton')"

[[plugins]]
repo = 'kei-s16/skkeleton-azik-kanatable'
on_source = 'skkeleton'
depends = ['skkeleton']
