[[plugins]]
repo = 'Shougo/ddu.vim'
depends = [
    'denops.vim',
    'ddu-ui-ff',
    'ddu-commands.vim'
]
# TODO: lua_addを使うかたちに置きかえる
hook_add = '''
    call ddu#custom#patch_global(
        \ {
        \   'ui': 'ff',
        \   'sources': [
        \       {'name': 'file_rec', 'params': {}},
        \       {'name': 'file_old', 'params': {}},
        \       {'name': 'buffer', 'params': {}},
        \   ],
        \   'sourceParams': {
        \       'file_rec': {'ignoredDirectories': ['.git', 'node_modules', 'vendor', 'target', 'dist']},
        \       'file_old': {'ignoredDirectories': ['.git', 'node_modules', 'vendor', 'target', 'dist']},
        \   },
        \   'sourceOptions': {
        \     '_': {
        \       'matchers': ['matcher_substring'],
        \     },
        \   },
        \   'kindOptions': {
        \     'file': {
        \       'defaultAction': 'open',
        \     },
        \   }
        \ })

    autocmd FileType ddu-ff call s:ddu_my_settings()
    function! s:ddu_my_settings() abort
      nnoremap <buffer><silent> <CR>
            \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
      nnoremap <buffer><silent> <Space>
            \ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
      nnoremap <buffer><silent> i
            \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
      nnoremap <buffer><silent> q
            \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
    endfunction

    autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
    function! s:ddu_filter_my_settings() abort
      inoremap <buffer><silent> <CR>
      \ <Esc><Cmd>close<CR>
      nnoremap <buffer><silent> <CR>
      \ <Cmd>close<CR>
      nnoremap <buffer><silent> q
      \ <Cmd>close<CR>
    endfunction

    nmap <silent> <leader>o :<C-u>Ddu file_rec<CR>
    nmap <silent> <leader>r :<C-u>Ddu file_old<CR>
    nmap <silent> <leader>b :<C-u>Ddu buffer<CR>
'''

# ddu-ui
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
depends = [
    'ddu-source-file_rec',
    'ddu-source-file_old',
    'ddu-filter-matcher_substring',
    'ddu-kind-file',
    'ddu-source-buffer'
]

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo='Shougo/ddu-commands.vim'

# ddu-source
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'Shougo/ddu-source-file_old'

[[plugins]]
repo='shun/ddu-source-buffer'

# ddu-kind
[[plugins]]
repo = 'Shougo/ddu-kind-file'

