# Dark Powered Vim Plugins
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
lua_add = "require('plugins.deol')"

# dependencies
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

# 日本語関連のあれこれ
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-jp/autofmt'
hook_add = 'set formatexpr=autofmt#japanese#formatexpr()'

# テーマ
[[plugins]]
repo = 'lifepillar/vim-solarized8'
hook_add = '''
    set background=light
    colorscheme solarized8
    set termguicolors
'''

# ファイル依存系
[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'LeafCage/vimhelpgenerator'
